name: Validate the PR
on:
  pull_request:
    branches: [ main ]
jobs:
  deploy:
    name: Package
    runs-on: [ CAI-Enterprise ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install yarn
        run: npm install --global yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build website
        run: yarn build